set(HAVEQOP OFF)
set(HAVEQDP OFF)
set(HAVEQIO OFF)
set(HAVEQMP OFF)

if(WANTQOP)
    find_package(QOP REQUIRED)
    set(HAVEQOP ON)
    set(HAVEQDP ON)
    set(HAVEQIO ON)
    set(HAVEQMP ON)
endif()

if(NOT HAVEQIO AND WANTQIO)
    find_package(QIO REQUIRED)
    set(HAVEQIO ON)
    set(HAVEQMP ON)
endif()

if(NOT HAVEQMP AND WANTQMP)
    find_package(QMP REQUIRED)
    set(HAVEQMP ON)
endif()

add_library(scidac INTERFACE)

if(HAVEQOP)
    target_compile_definitions(scidac INTERFACE HAVE_QOP QOP_PrecisionInt=${PRECISION})
    target_link_libraries(scidac INTERFACE QOP::qop)
endif()
if(HAVEQIO)
    target_compile_definitions(scidac INTERFACE HAVE_QIO)
    target_link_libraries(scidac INTERFACE QIO::qio)
endif()
if(HAVEQMP)
    if(MPP)
        target_compile_definitions(scidac INTERFACE HAVE_QMP QMP_MPI)
    else()
        target_compile_definitions(scidac INTERFACE HAVE_QMP QMP_SPI)
    endif()
    target_link_libraries(scidac INTERFACE QMP::qmp)
endif()
