set(HAVEQOP OFF)
set(HAVEQDP OFF)
set(HAVEQIO OFF)
set(HAVEQMP OFF)

if(WANTQOP)
    find_package(QOP REQUIRED)
    set(HAVEQOP ON)
    set(HAVEQDP ON)
    set(HAVEQIO ON)
    set(HAVEQMP ON)
endif()

if(NOT HAVEQIO AND WANTQIO)
    find_package(QIO REQUIRED)
    set(HAVEQIO ON)
    set(HAVEQMP ON)
endif()

if(NOT HAVEQMP AND WANTQMP)
    find_package(QMP REQUIRED)
    set(HAVEQMP ON)
endif()

set(cscidac)
if(HAVEQOP)
    list(APPEND cscidac HAVE_QOP QOP_PrecisionInt=${PRECISION})
endif()
if(HAVEQDP)
    list(APPEND cscidac HAVE_QDP QDP_PrecisionInt=${PRECISION})
endif()
if(HAVEQIO)
    list(APPEND cscidac HAVE_QIO)
endif()
if(HAVEQMP)
    list(APPEND cscidac HAVE_QMP)
    list(APPEND cscidac QMP_MPI)
endif()

add_library(scidac INTERFACE)
if(HAVEQOP)
    target_link_libraries(scidac INTERFACE QOP::qop)
elseif(HAVEQIO)
    target_link_libraries(scidac INTERFACE QIO::qio)
elseif(HAVEQMP)
    target_link_libraries(scidac INTERFACE QMP::qmp)
endif()
