# For generating correlation functions and form factor ratios

test3:
	make -f Make_select ff.bvtp_p0_sq0_zk0_q00 MATELNAME=bvtp "PMOM=0" "SQ=0" "ZK=0" "QMOM=00"
	make -f Make_select ff.bvtp_p0_sq0_zk0_q01 MATELNAME=bvtp "PMOM=0" "SQ=0" "ZK=0" "QMOM=01"
	make -f Make_select ff.bvtp_p0_sq0_zk0_q02 MATELNAME=bvtp "PMOM=0" "SQ=0" "ZK=0" "QMOM=02"
	make -f Make_select ff.bvtp_p0_sq0_zk0_q03 MATELNAME=bvtp "PMOM=0" "SQ=0" "ZK=0" "QMOM=03"
	make -f Make_select ff.bvtp_p0_sq0_zk0_q04 MATELNAME=bvtp "PMOM=0" "SQ=0" "ZK=0" "QMOM=04"
	make -f Make_select ff.bvtp_p0_sq0_zk0_q05 MATELNAME=bvtp "PMOM=0" "SQ=0" "ZK=0" "QMOM=05"
	make -f Make_select ff.bvtp_p0_sq0_zk0_q06 MATELNAME=bvtp "PMOM=0" "SQ=0" "ZK=0" "QMOM=06"
	make -f Make_select ff.bvtp_p0_sq0_zk0_q07 MATELNAME=bvtp "PMOM=0" "SQ=0" "ZK=0" "QMOM=07"
	make -f Make_select ff.bvtp_p0_sq0_zk0_q08 MATELNAME=bvtp "PMOM=0" "SQ=0" "ZK=0" "QMOM=08"
	make -f Make_select ff.bvtp_p0_sq0_zk0_q09 MATELNAME=bvtp "PMOM=0" "SQ=0" "ZK=0" "QMOM=09"
	make -f Make_select ff.bvtp_p0_sq0_zk0_q11 MATELNAME=bvtp "PMOM=0" "SQ=0" "ZK=0" "QMOM=11"

test2:
	make -f Make_select ms.b_GG_zk0_k00 "TWOPTNAME=b_GG" "ZK=0" "KMOM=00"
	make -f Make_select ms.b_GL_zk0_k00 "TWOPTNAME=b_GL" "ZK=0" "KMOM=00"
	make -f Make_select ms.b_GE_zk0_k00 "TWOPTNAME=b_GE" "ZK=0" "KMOM=00"
	make -f Make_select ms.p_GG_zk0_k00 "TWOPTNAME=p_GG" "ZK=0" "KMOM=00"


