#include "inline_C_addmat.h"
#include "inline_C_addvec.h"
#include "inline_C_m_mat_hwvec.h"
#include "inline_C_m_mat_na.h"
#include "inline_C_m_mat_nn.h"
#include "inline_C_msq_su3vec.h"
#include "inline_C_s_m_a_hwvec_proj.h"
#include "inline_C_s_m_a_mat.h"
#include "inline_C_s_m_a_vec.h"
#include "inline_C_su3_proj.h"
#include "inline_C_su3_rdot.h"
#include "inline_C_subvec.h"

